name: CI

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6','2.7','3.0' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install latest bundler
        run: gem install bundler
      - name: Install rubocop
        run: bundle install
      - name: Rubocop
        run: rubocop
      - name: Build Gem
        run: gem build *.gemspec
